### PR TITLE
Fix warnings module import in fx code

### PR DESCRIPTION
**Pull request by albanD**
Replicate the core change from https://github.com/pytorch/pytorch/pull/82760

### CODE REVIEW

**Review by jamesr66a — APPROVED** [review]
LGTM. FYI @Chillee since you added these callsites

**Review by wanchaol — APPROVED** [review]
blind stamp ;)

**Comment by albanD** [comment]
What's the merge process here? Should I click squash and merge directly?

**Comment by wanchaol** [comment]
> What's the merge process here? Should I click squash and merge directly?

that's usually what I do as long as ci passed

**Pull request merged**
