### PR TITLE
mnist example update to new compile stage API

### PR DESCRIPTION
**Pull request by eddogola**
## Description

Update the mnist example to use the new compile_stage api

## Checklist:

- [x] Has code been commented, particularly in hard-to-understand areas?

### CODE REVIEW

**Comment by eddogola** [comment]
https://www.internalfb.com/phabricator/paste/view/P782391812

**Comment by eddogola** [comment]
See new error here: https://www.internalfb.com/phabricator/paste/view/P784276221

**Comment by eddogola** [comment]
I'm currently saving the ckpts for each epoch in its own directory s.t. if were saving for every 500 epochs, there is a dir under "checkpoints"(or whatever other string that may be set as the checkpoint_dir) called 500, another 1000, and so on. What do you think of this design choice?

**Comment by wz337** [comment]
Could you double check the files changed to make sure that the change is reflected correctly?

**Review by wz337 — APPROVED** [review]
LGTM!

**Pull request merged**
